name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: 📦 Get LFTP
      run: sudo apt install lftp
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: Deploy files via SFTP
      run: ls public/build
