name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: 📦 Get LFTP
      run: sudo apt install lftp
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: Deploy files via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: ${{ secrets.FTP_PATH }}
        port: 22
        user: ${{ secrets.FTP_USER }}
        pass: ${{ secrets.FTP_PASS }}
          # lftp settings
        onlyNewer: true
        settings: 'sftp:auto-confirm=yes'
          # Mirror command options
        localDir: 'public/build'
        remoteDir: 'lehnhausen.dev'
        reverse: true
        ignoreFile: '.lftp_ignore'
        options: '--verbose'
