name: Clojure CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0    
    - name: Install dependencies
      run: lein deps
    - name: Build notebook
      run: lein run
    - name: Deploy files via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: "host243.checkdomain.de"
        port: 22
        user: ${{ secrets.FTP_USER }}
        pass: ${{ secrets.FTP_PASS }}
          # lftp settings
        onlyNewer: false
        settings: 'sftp:auto-confirm=yes'
          # Mirror command options
        localDir: 'public/build/'
        remoteDir: 'lehnhausen.dev'
        reverse: true
        ignoreFile: '.lftp_ignore'
        options: '--verbose'
